repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3
        additional_dependencies: ["click<8.1.4"]
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.5
    hooks:
      - id: ruff
        args: ["--fix"]
  - repo: https://github.com/python-poetry/poetry
    rev: '1.8.3'
    hooks:
      - id: poetry-check
        files: "^$"  # disabled unless poetry is present
        stages: [manual]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        additional_dependencies: ["prettier@3.3.3"]
        files: "\.(json|md|yml|yaml|ts|tsx|js|css|scss|html)$"
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.9.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@9.9.0
          - "@eslint/js@^9.9.0"
          - typescript@^5.5.3
          - typescript-eslint@^8.0.1
          - eslint-plugin-react-hooks@^5.1.0-rc.0
          - eslint-plugin-react-refresh@^0.4.9
        files: "^src/|^mobile/"
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
        args: ["detect", "--no-git", "--redact"]